### ISSUE TITLE
"Object" is reserved since PHP7

### ISSUE THREAD

**Issue by bitbayio** [rygilles/laravel-api-boilerplate#1]
first "composer install" throws error 

PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/vendor/rygilles/laravel-openapi-schema-generator/src/Rygilles/OpenApiGenerator/OpenApi/Object.php on line 17

System : Docker( alpine3.6/php7.2/nginx )

I think that  if u rename "Object" to something like "BaseObject" will solve the problem because I dont think a workaround makes sense ... or what do you think ? I like the architecture of ur API and i`m really interested to test it with my docker container because thats how i use them in production and downgrading is a nogo.

**Comment by rygilles** [comment]
Thanks for trying my code and sorry for this late response.
I have updated my generator lib so now there's no more "Object" class in the last release : https://github.com/rygilles/laravel-api-boilerplate/releases/tag/v0.2.4

**Comment by bitbayio** [comment]
nice work, problem is solved. Sad to see that this high quality project  does not get the attention it deserves
